export default {
"login": "thirihsumyataung",
"id": 61168937,
"node_id": "MDQ6VXNlcjYxMTY4OTM3",
"avatar_url": "https://avatars.githubusercontent.com/u/61168937?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/thirihsumyataung",
"html_url": "https://github.com/thirihsumyataung",
"followers_url": "https://api.github.com/users/thirihsumyataung/followers",
"following_url": "https://api.github.com/users/thirihsumyataung/following{/other_user}",
"gists_url": "https://api.github.com/users/thirihsumyataung/gists{/gist_id}",
"starred_url": "https://api.github.com/users/thirihsumyataung/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/thirihsumyataung/subscriptions",
"organizations_url": "https://api.github.com/users/thirihsumyataung/orgs",
"repos_url": "https://api.github.com/users/thirihsumyataung/repos",
"events_url": "https://api.github.com/users/thirihsumyataung/events{/privacy}",
"received_events_url": "https://api.github.com/users/thirihsumyataung/received_events",
"type": "User",
"site_admin": false,
"name": "Ying Tee",
"company": null,
"blog": "",
"location": "Rockville, Maryland, USA",
"email": null,
"hireable": true,
"bio": null,
"twitter_username": "YangMoriwoh",
"public_repos": 17,
"public_gists": 0,
"followers": 2,
"following": 10,
"created_at": "2020-02-17T23:32:02Z",
"updated_at": "2021-05-27T18:02:30Z"
};